"""checkpoints

Revision ID: 20e40a84c706
Revises: f3a1ec2e37f6
Create Date: 2024-10-26 10:41:58.138297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20e40a84c706'
down_revision = 'f3a1ec2e37f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('checkpoint_ns', sa.Text(), server_default='', nullable=False),
    sa.Column('checkpoint_id', sa.Text(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
