"""strategies code

Revision ID: 2920153f5347
Revises: 7703d921959e
Create Date: 2025-01-02 15:39:19.256806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2920153f5347'
down_revision = '7703d921959e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('code', sa.TEXT(), nullable=False))
    op.drop_constraint('strategies_chat_id_key', 'strategies', type_='unique')
    op.drop_constraint('strategies_chat_id_fkey', 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('strategies_chat_id_fkey', 'strategies', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('strategies_chat_id_key', 'strategies', ['chat_id'])
    op.drop_column('strategies', 'code')
    # ### end Alembic commands ###
