"""Add users

Revision ID: 4f1038a5635d
Revises: f5d58c9eae14
Create Date: 2024-10-25 19:34:01.496028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1038a5635d'
down_revision = 'f5d58c9eae14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chats', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.drop_column('chats', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
