"""stragies users

Revision ID: 65610e92cb70
Revises: 2920153f5347
Create Date: 2025-01-02 16:01:30.990204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65610e92cb70'
down_revision = '2920153f5347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'strategies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'user_id')
    # ### end Alembic commands ###
