"""fix cascade

Revision ID: 7703d921959e
Revises: 48ce389f887d
Create Date: 2024-11-04 10:20:53.153301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7703d921959e'
down_revision = '48ce389f887d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('strategies_chat_id_fkey', 'strategies', type_='foreignkey')
    op.create_foreign_key(None, 'strategies', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.create_foreign_key('strategies_chat_id_fkey', 'strategies', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
