"""unique_chat_thread_id

Revision ID: 7fb972aefde9
Revises: 8670cc3168bc
Create Date: 2024-10-29 20:05:20.892546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb972aefde9'
down_revision = '8670cc3168bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chats', ['thread_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    # ### end Alembic commands ###
