"""add strategy draft

Revision ID: c7b2a7ec5fc3
Revises: 134e334b5840
Create Date: 2025-01-11 14:20:09.235214

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7b2a7ec5fc3"
down_revision = "134e334b5840"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategies", sa.Column("draft", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategies", "draft")
    # ### end Alembic commands ###
