"""clerk_id unique

Revision ID: c806013d8d2b
Revises: 4f1038a5635d
Create Date: 2024-10-25 21:41:59.644216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c806013d8d2b'
down_revision = '4f1038a5635d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['clerk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
