"""checkpoints

Revision ID: f3a1ec2e37f6
Revises: effeeca9d7c9
Create Date: 2024-10-26 10:36:19.275380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a1ec2e37f6'
down_revision = 'effeeca9d7c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('users_id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
