"""Add chat_id to strategies

Revision ID: f6e1fc4721fc
Revises: c7b2a7ec5fc3
Create Date: 2025-01-13 19:09:34.783051

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6e1fc4721fc"
down_revision = "c7b2a7ec5fc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategies", sa.Column("chat_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "strategies", "chats", ["chat_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "strategies", type_="foreignkey")
    op.drop_column("strategies", "chat_id")
    # ### end Alembic commands ###
